package fev1.dif.afip.gov.ar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-31T14:57:55.034+01:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://ar.gov.afip.dif.FEV1/", name = "ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoap {

    /**
     * Consulta CAEA informado como sin movimientos.
     */
    @WebMethod(operationName = "FECAEASinMovimientoConsultar", action = "http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoConsultar")
    @RequestWrapper(localName = "FECAEASinMovimientoConsultar", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FECAEASinMovimientoConsultar")
    @ResponseWrapper(localName = "FECAEASinMovimientoConsultarResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FECAEASinMovimientoConsultarResponse")
    @WebResult(name = "FECAEASinMovimientoConsultarResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.FECAEASinMovConsResponse fecaeaSinMovimientoConsultar(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth,
        @WebParam(name = "CAEA", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        java.lang.String caea,
        @WebParam(name = "PtoVta", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        int ptoVta
    );

    /**
     * Recupera el listado  de Tipos de Iva utilizables en servicio de autorización.
     */
    @WebMethod(operationName = "FEParamGetTiposIva", action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposIva")
    @RequestWrapper(localName = "FEParamGetTiposIva", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetTiposIva")
    @ResponseWrapper(localName = "FEParamGetTiposIvaResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetTiposIvaResponse")
    @WebResult(name = "FEParamGetTiposIvaResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.IvaTipoResponse feParamGetTiposIva(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth
    );

    /**
     * Informa CAEA sin movimientos.
     */
    @WebMethod(operationName = "FECAEASinMovimientoInformar", action = "http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoInformar")
    @RequestWrapper(localName = "FECAEASinMovimientoInformar", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FECAEASinMovimientoInformar")
    @ResponseWrapper(localName = "FECAEASinMovimientoInformarResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FECAEASinMovimientoInformarResponse")
    @WebResult(name = "FECAEASinMovimientoInformarResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.FECAEASinMovResponse fecaeaSinMovimientoInformar(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth,
        @WebParam(name = "PtoVta", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        int ptoVta,
        @WebParam(name = "CAEA", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        java.lang.String caea
    );

    /**
     * Retorna el ultimo comprobante autorizado para el tipo de comprobante / cuit / punto de venta ingresado / Tipo de Emisión
     */
    @WebMethod(operationName = "FECompUltimoAutorizado", action = "http://ar.gov.afip.dif.FEV1/FECompUltimoAutorizado")
    @RequestWrapper(localName = "FECompUltimoAutorizado", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FECompUltimoAutorizado")
    @ResponseWrapper(localName = "FECompUltimoAutorizadoResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FECompUltimoAutorizadoResponse")
    @WebResult(name = "FECompUltimoAutorizadoResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.FERecuperaLastCbteResponse feCompUltimoAutorizado(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth,
        @WebParam(name = "PtoVta", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        int ptoVta,
        @WebParam(name = "CbteTipo", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        int cbteTipo
    );

    /**
     * Recupera el listado de puntos de venta registrados y su estado
     */
    @WebMethod(operationName = "FEParamGetPtosVenta", action = "http://ar.gov.afip.dif.FEV1/FEParamGetPtosVenta")
    @RequestWrapper(localName = "FEParamGetPtosVenta", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetPtosVenta")
    @ResponseWrapper(localName = "FEParamGetPtosVentaResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetPtosVentaResponse")
    @WebResult(name = "FEParamGetPtosVentaResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.FEPtoVentaResponse feParamGetPtosVenta(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth
    );

    /**
     * Solicitud de Código de Autorización Electrónico (CAE)
     */
    @WebMethod(operationName = "FECAESolicitar", action = "http://ar.gov.afip.dif.FEV1/FECAESolicitar")
    @RequestWrapper(localName = "FECAESolicitar", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FECAESolicitar")
    @ResponseWrapper(localName = "FECAESolicitarResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FECAESolicitarResponse")
    @WebResult(name = "FECAESolicitarResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.FECAEResponse fecaeSolicitar(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth,
        @WebParam(name = "FeCAEReq", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FECAERequest feCAEReq
    );

    /**
     * Consultar CAEA emitidos.
     */
    @WebMethod(operationName = "FECAEAConsultar", action = "http://ar.gov.afip.dif.FEV1/FECAEAConsultar")
    @RequestWrapper(localName = "FECAEAConsultar", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FECAEAConsultar")
    @ResponseWrapper(localName = "FECAEAConsultarResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FECAEAConsultarResponse")
    @WebResult(name = "FECAEAConsultarResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.FECAEAGetResponse fecaeaConsultar(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth,
        @WebParam(name = "Periodo", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        int periodo,
        @WebParam(name = "Orden", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        short orden
    );

    /**
     * Metodo dummy para verificacion de funcionamiento
     */
    @WebMethod(operationName = "FEDummy", action = "http://ar.gov.afip.dif.FEV1/FEDummy")
    @RequestWrapper(localName = "FEDummy", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEDummy")
    @ResponseWrapper(localName = "FEDummyResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEDummyResponse")
    @WebResult(name = "FEDummyResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.DummyResponse feDummy();

    /**
     * Recupera el listado  de identificadores para el campo Concepto.
     */
    @WebMethod(operationName = "FEParamGetTiposConcepto", action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposConcepto")
    @RequestWrapper(localName = "FEParamGetTiposConcepto", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetTiposConcepto")
    @ResponseWrapper(localName = "FEParamGetTiposConceptoResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetTiposConceptoResponse")
    @WebResult(name = "FEParamGetTiposConceptoResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.ConceptoTipoResponse feParamGetTiposConcepto(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth
    );

    /**
     * Recupera el listado de monedas utilizables en servicio de autorización
     */
    @WebMethod(operationName = "FEParamGetTiposMonedas", action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposMonedas")
    @RequestWrapper(localName = "FEParamGetTiposMonedas", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetTiposMonedas")
    @ResponseWrapper(localName = "FEParamGetTiposMonedasResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetTiposMonedasResponse")
    @WebResult(name = "FEParamGetTiposMonedasResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.MonedaResponse feParamGetTiposMonedas(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth
    );

    /**
     * Retorna la cantidad maxima de registros que puede tener una invocacion al metodo FECAESolicitar / FECAEARegInformativo 
     */
    @WebMethod(operationName = "FECompTotXRequest", action = "http://ar.gov.afip.dif.FEV1/FECompTotXRequest")
    @RequestWrapper(localName = "FECompTotXRequest", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FECompTotXRequest")
    @ResponseWrapper(localName = "FECompTotXRequestResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FECompTotXRequestResponse")
    @WebResult(name = "FECompTotXRequestResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.FERegXReqResponse feCompTotXRequest(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth
    );

    /**
     * Rendición de comprobantes asociados a un CAEA.
     */
    @WebMethod(operationName = "FECAEARegInformativo", action = "http://ar.gov.afip.dif.FEV1/FECAEARegInformativo")
    @RequestWrapper(localName = "FECAEARegInformativo", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FECAEARegInformativo")
    @ResponseWrapper(localName = "FECAEARegInformativoResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FECAEARegInformativoResponse")
    @WebResult(name = "FECAEARegInformativoResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.FECAEAResponse fecaeaRegInformativo(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth,
        @WebParam(name = "FeCAEARegInfReq", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FECAEARequest feCAEARegInfReq
    );

    /**
     * Recupera el listado de identificadores para los campos Opcionales
     */
    @WebMethod(operationName = "FEParamGetTiposOpcional", action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposOpcional")
    @RequestWrapper(localName = "FEParamGetTiposOpcional", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetTiposOpcional")
    @ResponseWrapper(localName = "FEParamGetTiposOpcionalResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetTiposOpcionalResponse")
    @WebResult(name = "FEParamGetTiposOpcionalResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.OpcionalTipoResponse feParamGetTiposOpcional(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth
    );

    /**
     * Recupera la cotizacion de la moneda consultada y su  fecha 
     */
    @WebMethod(operationName = "FEParamGetCotizacion", action = "http://ar.gov.afip.dif.FEV1/FEParamGetCotizacion")
    @RequestWrapper(localName = "FEParamGetCotizacion", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetCotizacion")
    @ResponseWrapper(localName = "FEParamGetCotizacionResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetCotizacionResponse")
    @WebResult(name = "FEParamGetCotizacionResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.FECotizacionResponse feParamGetCotizacion(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth,
        @WebParam(name = "MonId", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        java.lang.String monId
    );

    /**
     * Recupera el listado de los diferente paises que pueden ser utilizados  en el servicio de autorizacion
     */
    @WebMethod(operationName = "FEParamGetTiposPaises", action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposPaises")
    @RequestWrapper(localName = "FEParamGetTiposPaises", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetTiposPaises")
    @ResponseWrapper(localName = "FEParamGetTiposPaisesResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetTiposPaisesResponse")
    @WebResult(name = "FEParamGetTiposPaisesResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.FEPaisResponse feParamGetTiposPaises(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth
    );

    /**
     * Solicitud de Código de Autorización Electrónico Anticipado (CAEA)
     */
    @WebMethod(operationName = "FECAEASolicitar", action = "http://ar.gov.afip.dif.FEV1/FECAEASolicitar")
    @RequestWrapper(localName = "FECAEASolicitar", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FECAEASolicitar")
    @ResponseWrapper(localName = "FECAEASolicitarResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FECAEASolicitarResponse")
    @WebResult(name = "FECAEASolicitarResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.FECAEAGetResponse fecaeaSolicitar(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth,
        @WebParam(name = "Periodo", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        int periodo,
        @WebParam(name = "Orden", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        short orden
    );

    /**
     * Recupera el listado de los diferente tributos que pueden ser utilizados  en el servicio de autorizacion
     */
    @WebMethod(operationName = "FEParamGetTiposTributos", action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposTributos")
    @RequestWrapper(localName = "FEParamGetTiposTributos", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetTiposTributos")
    @ResponseWrapper(localName = "FEParamGetTiposTributosResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetTiposTributosResponse")
    @WebResult(name = "FEParamGetTiposTributosResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.FETributoResponse feParamGetTiposTributos(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth
    );

    /**
     * Consulta Comprobante emitido y su código.
     */
    @WebMethod(operationName = "FECompConsultar", action = "http://ar.gov.afip.dif.FEV1/FECompConsultar")
    @RequestWrapper(localName = "FECompConsultar", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FECompConsultar")
    @ResponseWrapper(localName = "FECompConsultarResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FECompConsultarResponse")
    @WebResult(name = "FECompConsultarResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.FECompConsultaResponse feCompConsultar(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth,
        @WebParam(name = "FeCompConsReq", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FECompConsultaReq feCompConsReq
    );

    /**
     * Recupera el listado  de Tipos de Comprobantes utilizables en servicio de autorización.
     */
    @WebMethod(operationName = "FEParamGetTiposCbte", action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposCbte")
    @RequestWrapper(localName = "FEParamGetTiposCbte", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetTiposCbte")
    @ResponseWrapper(localName = "FEParamGetTiposCbteResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetTiposCbteResponse")
    @WebResult(name = "FEParamGetTiposCbteResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.CbteTipoResponse feParamGetTiposCbte(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth
    );

    /**
     * Recupera el listado  de Tipos de Documentos utilizables en servicio de autorización.
     */
    @WebMethod(operationName = "FEParamGetTiposDoc", action = "http://ar.gov.afip.dif.FEV1/FEParamGetTiposDoc")
    @RequestWrapper(localName = "FEParamGetTiposDoc", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetTiposDoc")
    @ResponseWrapper(localName = "FEParamGetTiposDocResponse", targetNamespace = "http://ar.gov.afip.dif.FEV1/", className = "fev1.dif.afip.gov.ar.FEParamGetTiposDocResponse")
    @WebResult(name = "FEParamGetTiposDocResult", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
    public fev1.dif.afip.gov.ar.DocTipoResponse feParamGetTiposDoc(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.FEV1/")
        fev1.dif.afip.gov.ar.FEAuthRequest auth
    );
}
