package com.liciusit.ws.afip.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="https://wswhomo.afip.gov.ar/wsfev1/service.asmx?WSDL",
  targetNamespace="http://ar.gov.afip.dif.FEV1/", name="ServiceSoap")
@XmlSeeAlso(
  { com.liciusit.ws.afip.client.types.ObjectFactory.class })
public interface ServiceSoap
{
  @WebMethod(operationName="FECAESolicitar", action="http://ar.gov.afip.dif.FEV1/FECAESolicitar")
  @Action(input="http://ar.gov.afip.dif.FEV1/FECAESolicitar", output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FECAESolicitarResponse")
  @ResponseWrapper(localName="FECAESolicitarResponse", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FECAESolicitarResponse")
  @RequestWrapper(localName="FECAESolicitar", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FECAESolicitar")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FECAESolicitarResult")
  public com.liciusit.ws.afip.client.types.FECAEResponse fecaeSolicitar(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth,
    @WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FeCAEReq")
    com.liciusit.ws.afip.client.types.FECAERequest feCAEReq);

  @WebMethod(operationName="FECompTotXRequest", action="http://ar.gov.afip.dif.FEV1/FECompTotXRequest")
  @Action(input="http://ar.gov.afip.dif.FEV1/FECompTotXRequest", output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FECompTotXRequestResponse")
  @ResponseWrapper(localName="FECompTotXRequestResponse", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FECompTotXRequestResponse")
  @RequestWrapper(localName="FECompTotXRequest", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FECompTotXRequest")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FECompTotXRequestResult")
  public com.liciusit.ws.afip.client.types.FERegXReqResponse feCompTotXRequest(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth);

  @WebMethod(operationName="FEDummy", action="http://ar.gov.afip.dif.FEV1/FEDummy")
  @Action(input="http://ar.gov.afip.dif.FEV1/FEDummy", output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FEDummyResponse")
  @ResponseWrapper(localName="FEDummyResponse", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FEDummyResponse")
  @RequestWrapper(localName="FEDummy", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FEDummy")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FEDummyResult")
  public com.liciusit.ws.afip.client.types.DummyResponse feDummy();

  @WebMethod(operationName="FECompUltimoAutorizado", action="http://ar.gov.afip.dif.FEV1/FECompUltimoAutorizado")
  @Action(input="http://ar.gov.afip.dif.FEV1/FECompUltimoAutorizado",
    output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FECompUltimoAutorizadoResponse")
  @ResponseWrapper(localName="FECompUltimoAutorizadoResponse",
    targetNamespace="http://ar.gov.afip.dif.FEV1/", className="com.liciusit.ws.afip.client.types.FECompUltimoAutorizadoResponse")
  @RequestWrapper(localName="FECompUltimoAutorizado", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FECompUltimoAutorizado")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FECompUltimoAutorizadoResult")
  public com.liciusit.ws.afip.client.types.FERecuperaLastCbteResponse feCompUltimoAutorizado(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth,
    @WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="PtoVta")
    int ptoVta, @WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="CbteTipo")
    int cbteTipo);

  @WebMethod(operationName="FECompConsultar", action="http://ar.gov.afip.dif.FEV1/FECompConsultar")
  @Action(input="http://ar.gov.afip.dif.FEV1/FECompConsultar", output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FECompConsultarResponse")
  @ResponseWrapper(localName="FECompConsultarResponse", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FECompConsultarResponse")
  @RequestWrapper(localName="FECompConsultar", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FECompConsultar")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FECompConsultarResult")
  public com.liciusit.ws.afip.client.types.FECompConsultaResponse feCompConsultar(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth,
    @WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FeCompConsReq")
    com.liciusit.ws.afip.client.types.FECompConsultaReq feCompConsReq);

  @WebMethod(operationName="FECAEARegInformativo", action="http://ar.gov.afip.dif.FEV1/FECAEARegInformativo")
  @Action(input="http://ar.gov.afip.dif.FEV1/FECAEARegInformativo",
    output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FECAEARegInformativoResponse")
  @ResponseWrapper(localName="FECAEARegInformativoResponse",
    targetNamespace="http://ar.gov.afip.dif.FEV1/", className="com.liciusit.ws.afip.client.types.FECAEARegInformativoResponse")
  @RequestWrapper(localName="FECAEARegInformativo", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FECAEARegInformativo")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FECAEARegInformativoResult")
  public com.liciusit.ws.afip.client.types.FECAEAResponse fecaeaRegInformativo(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth,
    @WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FeCAEARegInfReq")
    com.liciusit.ws.afip.client.types.FECAEARequest feCAEARegInfReq);

  @WebMethod(operationName="FECAEASolicitar", action="http://ar.gov.afip.dif.FEV1/FECAEASolicitar")
  @Action(input="http://ar.gov.afip.dif.FEV1/FECAEASolicitar", output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FECAEASolicitarResponse")
  @ResponseWrapper(localName="FECAEASolicitarResponse", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FECAEASolicitarResponse")
  @RequestWrapper(localName="FECAEASolicitar", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FECAEASolicitar")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FECAEASolicitarResult")
  public com.liciusit.ws.afip.client.types.FECAEAGetResponse fecaeaSolicitar(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth,
    @WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="Periodo")
    int periodo, @WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Orden")
    short orden);

  @WebMethod(operationName="FECAEASinMovimientoConsultar", action="http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoConsultar")
  @Action(input="http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoConsultar",
    output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FECAEASinMovimientoConsultarResponse")
  @ResponseWrapper(localName="FECAEASinMovimientoConsultarResponse",
    targetNamespace="http://ar.gov.afip.dif.FEV1/", className="com.liciusit.ws.afip.client.types.FECAEASinMovimientoConsultarResponse")
  @RequestWrapper(localName="FECAEASinMovimientoConsultar",
    targetNamespace="http://ar.gov.afip.dif.FEV1/", className="com.liciusit.ws.afip.client.types.FECAEASinMovimientoConsultar")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FECAEASinMovimientoConsultarResult")
  public com.liciusit.ws.afip.client.types.FECAEASinMovConsResponse fecaeaSinMovimientoConsultar(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth,
    @WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="CAEA")
    String caea, @WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="PtoVta")
    int ptoVta);

  @WebMethod(operationName="FECAEASinMovimientoInformar", action="http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoInformar")
  @Action(input="http://ar.gov.afip.dif.FEV1/FECAEASinMovimientoInformar",
    output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FECAEASinMovimientoInformarResponse")
  @ResponseWrapper(localName="FECAEASinMovimientoInformarResponse",
    targetNamespace="http://ar.gov.afip.dif.FEV1/", className="com.liciusit.ws.afip.client.types.FECAEASinMovimientoInformarResponse")
  @RequestWrapper(localName="FECAEASinMovimientoInformar",
    targetNamespace="http://ar.gov.afip.dif.FEV1/", className="com.liciusit.ws.afip.client.types.FECAEASinMovimientoInformar")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FECAEASinMovimientoInformarResult")
  public com.liciusit.ws.afip.client.types.FECAEASinMovResponse fecaeaSinMovimientoInformar(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth,
    @WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="PtoVta")
    int ptoVta, @WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="CAEA")
    String caea);

  @WebMethod(operationName="FECAEAConsultar", action="http://ar.gov.afip.dif.FEV1/FECAEAConsultar")
  @Action(input="http://ar.gov.afip.dif.FEV1/FECAEAConsultar", output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FECAEAConsultarResponse")
  @ResponseWrapper(localName="FECAEAConsultarResponse", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FECAEAConsultarResponse")
  @RequestWrapper(localName="FECAEAConsultar", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FECAEAConsultar")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FECAEAConsultarResult")
  public com.liciusit.ws.afip.client.types.FECAEAGetResponse fecaeaConsultar(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth,
    @WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="Periodo")
    int periodo, @WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Orden")
    short orden);

  @WebMethod(operationName="FEParamGetCotizacion", action="http://ar.gov.afip.dif.FEV1/FEParamGetCotizacion")
  @Action(input="http://ar.gov.afip.dif.FEV1/FEParamGetCotizacion",
    output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FEParamGetCotizacionResponse")
  @ResponseWrapper(localName="FEParamGetCotizacionResponse",
    targetNamespace="http://ar.gov.afip.dif.FEV1/", className="com.liciusit.ws.afip.client.types.FEParamGetCotizacionResponse")
  @RequestWrapper(localName="FEParamGetCotizacion", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FEParamGetCotizacion")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FEParamGetCotizacionResult")
  public com.liciusit.ws.afip.client.types.FECotizacionResponse feParamGetCotizacion(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth,
    @WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="MonId")
    String monId);

  @WebMethod(operationName="FEParamGetTiposTributos", action="http://ar.gov.afip.dif.FEV1/FEParamGetTiposTributos")
  @Action(input="http://ar.gov.afip.dif.FEV1/FEParamGetTiposTributos",
    output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FEParamGetTiposTributosResponse")
  @ResponseWrapper(localName="FEParamGetTiposTributosResponse",
    targetNamespace="http://ar.gov.afip.dif.FEV1/", className="com.liciusit.ws.afip.client.types.FEParamGetTiposTributosResponse")
  @RequestWrapper(localName="FEParamGetTiposTributos", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FEParamGetTiposTributos")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FEParamGetTiposTributosResult")
  public com.liciusit.ws.afip.client.types.FETributoResponse feParamGetTiposTributos(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth);

  @WebMethod(operationName="FEParamGetTiposMonedas", action="http://ar.gov.afip.dif.FEV1/FEParamGetTiposMonedas")
  @Action(input="http://ar.gov.afip.dif.FEV1/FEParamGetTiposMonedas",
    output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FEParamGetTiposMonedasResponse")
  @ResponseWrapper(localName="FEParamGetTiposMonedasResponse",
    targetNamespace="http://ar.gov.afip.dif.FEV1/", className="com.liciusit.ws.afip.client.types.FEParamGetTiposMonedasResponse")
  @RequestWrapper(localName="FEParamGetTiposMonedas", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FEParamGetTiposMonedas")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FEParamGetTiposMonedasResult")
  public com.liciusit.ws.afip.client.types.MonedaResponse feParamGetTiposMonedas(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth);

  @WebMethod(operationName="FEParamGetTiposIva", action="http://ar.gov.afip.dif.FEV1/FEParamGetTiposIva")
  @Action(input="http://ar.gov.afip.dif.FEV1/FEParamGetTiposIva", output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FEParamGetTiposIvaResponse")
  @ResponseWrapper(localName="FEParamGetTiposIvaResponse",
    targetNamespace="http://ar.gov.afip.dif.FEV1/", className="com.liciusit.ws.afip.client.types.FEParamGetTiposIvaResponse")
  @RequestWrapper(localName="FEParamGetTiposIva", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FEParamGetTiposIva")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FEParamGetTiposIvaResult")
  public com.liciusit.ws.afip.client.types.IvaTipoResponse feParamGetTiposIva(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth);

  @WebMethod(operationName="FEParamGetTiposOpcional", action="http://ar.gov.afip.dif.FEV1/FEParamGetTiposOpcional")
  @Action(input="http://ar.gov.afip.dif.FEV1/FEParamGetTiposOpcional",
    output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FEParamGetTiposOpcionalResponse")
  @ResponseWrapper(localName="FEParamGetTiposOpcionalResponse",
    targetNamespace="http://ar.gov.afip.dif.FEV1/", className="com.liciusit.ws.afip.client.types.FEParamGetTiposOpcionalResponse")
  @RequestWrapper(localName="FEParamGetTiposOpcional", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FEParamGetTiposOpcional")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FEParamGetTiposOpcionalResult")
  public com.liciusit.ws.afip.client.types.OpcionalTipoResponse feParamGetTiposOpcional(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth);

  @WebMethod(operationName="FEParamGetTiposConcepto", action="http://ar.gov.afip.dif.FEV1/FEParamGetTiposConcepto")
  @Action(input="http://ar.gov.afip.dif.FEV1/FEParamGetTiposConcepto",
    output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FEParamGetTiposConceptoResponse")
  @ResponseWrapper(localName="FEParamGetTiposConceptoResponse",
    targetNamespace="http://ar.gov.afip.dif.FEV1/", className="com.liciusit.ws.afip.client.types.FEParamGetTiposConceptoResponse")
  @RequestWrapper(localName="FEParamGetTiposConcepto", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FEParamGetTiposConcepto")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FEParamGetTiposConceptoResult")
  public com.liciusit.ws.afip.client.types.ConceptoTipoResponse feParamGetTiposConcepto(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth);

  @WebMethod(operationName="FEParamGetPtosVenta", action="http://ar.gov.afip.dif.FEV1/FEParamGetPtosVenta")
  @Action(input="http://ar.gov.afip.dif.FEV1/FEParamGetPtosVenta", output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FEParamGetPtosVentaResponse")
  @ResponseWrapper(localName="FEParamGetPtosVentaResponse",
    targetNamespace="http://ar.gov.afip.dif.FEV1/", className="com.liciusit.ws.afip.client.types.FEParamGetPtosVentaResponse")
  @RequestWrapper(localName="FEParamGetPtosVenta", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FEParamGetPtosVenta")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FEParamGetPtosVentaResult")
  public com.liciusit.ws.afip.client.types.FEPtoVentaResponse feParamGetPtosVenta(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth);

  @WebMethod(operationName="FEParamGetTiposCbte", action="http://ar.gov.afip.dif.FEV1/FEParamGetTiposCbte")
  @Action(input="http://ar.gov.afip.dif.FEV1/FEParamGetTiposCbte", output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FEParamGetTiposCbteResponse")
  @ResponseWrapper(localName="FEParamGetTiposCbteResponse",
    targetNamespace="http://ar.gov.afip.dif.FEV1/", className="com.liciusit.ws.afip.client.types.FEParamGetTiposCbteResponse")
  @RequestWrapper(localName="FEParamGetTiposCbte", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FEParamGetTiposCbte")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FEParamGetTiposCbteResult")
  public com.liciusit.ws.afip.client.types.CbteTipoResponse feParamGetTiposCbte(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth);

  @WebMethod(operationName="FEParamGetTiposDoc", action="http://ar.gov.afip.dif.FEV1/FEParamGetTiposDoc")
  @Action(input="http://ar.gov.afip.dif.FEV1/FEParamGetTiposDoc", output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FEParamGetTiposDocResponse")
  @ResponseWrapper(localName="FEParamGetTiposDocResponse",
    targetNamespace="http://ar.gov.afip.dif.FEV1/", className="com.liciusit.ws.afip.client.types.FEParamGetTiposDocResponse")
  @RequestWrapper(localName="FEParamGetTiposDoc", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FEParamGetTiposDoc")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FEParamGetTiposDocResult")
  public com.liciusit.ws.afip.client.types.DocTipoResponse feParamGetTiposDoc(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth);

  @WebMethod(operationName="FEParamGetTiposPaises", action="http://ar.gov.afip.dif.FEV1/FEParamGetTiposPaises")
  @Action(input="http://ar.gov.afip.dif.FEV1/FEParamGetTiposPaises",
    output="http://ar.gov.afip.dif.FEV1/ServiceSoap/FEParamGetTiposPaisesResponse")
  @ResponseWrapper(localName="FEParamGetTiposPaisesResponse",
    targetNamespace="http://ar.gov.afip.dif.FEV1/", className="com.liciusit.ws.afip.client.types.FEParamGetTiposPaisesResponse")
  @RequestWrapper(localName="FEParamGetTiposPaises", targetNamespace="http://ar.gov.afip.dif.FEV1/",
    className="com.liciusit.ws.afip.client.types.FEParamGetTiposPaises")
  @WebResult(targetNamespace="http://ar.gov.afip.dif.FEV1/", name="FEParamGetTiposPaisesResult")
  public com.liciusit.ws.afip.client.types.FEPaisResponse feParamGetTiposPaises(@WebParam(targetNamespace="http://ar.gov.afip.dif.FEV1/",
      name="Auth")
    com.liciusit.ws.afip.client.types.FEAuthRequest auth);
}
